# Units:
# distance [m], speed [m/s], acceleration [m/s^2]

CARLA:
  DT: 0.05                                                       # Set to -1 for variable time-step (real-world simulation)
  LANE_WIDTH: 3.5                                               # [int] max frenet s value available in global route
  TASK_MODE: Lane                                               #'SingleFollow', 'DoubleFollowing', 'CrossJoin',
                                                                #'TurnLeft','TurnRight' or 'RingJoin'

POLICY:
  NAME: TRPO                                                    # DDPG/TRPO/PPO2/A2C
  NET: MLP                                                      # MLP/CNN/LSTM - DDPG does not have LSTM policy

GYM_ENV:
  TARGET_SPEED: 8.00 #13.89                                     # Ego's target speed
  MAX_SPEED: 16.00 #25
  MAX_ACC: 6.878                                                # equivalent to 24.7608 km/h.s for Tesla model 3
  LOOP_BREAK: 800                                               # max steps each episode

RL:
  LANE_CHANGE_PENALTY: 0.2                                      # Unnecesary Lane Change Penalty                                           # Collison penalty
  SIGMA_POS: 0.3
  SIGMA_ANGLE: 0.4
  SIGMAL_LOW_SPEED: 1.0
  SIGMAL_HIGH_SPEED: 0.6

TRAFFIC_MANAGER:
  N_SPAWN_CARS: 0                                              # number of cars spawned at each episode
  MIN_SPEED: 8.33                                               # Min speed for actors in random traffic
  MAX_SPEED: 15.00                                              # Max speed for actors in random traffic

LOCAL_PLANNER:
  MIN_SPEED: 5.56 # 5.56                                       # Allowed min speed for ego vehicle; RL's -1 action maps to this value
  MAX_SPEED: 15.28                                              # Allowed max speed for ego vehicle; RL's 1 action maps to this value
